const host = "http://localhost:5000"
export const signupRoute = `${host}/api/auth/signup`
export const loginRoute = `${host}/api/auth/login`
export const googleRoute = `${host}/api/auth/google`
export const newReport = `${host}/api/report/newReport`
export const resolveReport = `${host}/api/report/resolveReport`
export const newResponse = `${host}/api/report/newResponse`
export const fetchResponse = `${host}/api/report/fetchResponses`
export const allReports = `${host}/api/report/allReports`
export const newNotify = `${host}/api/notify/newNotify`
export const allNotify = `${host}/api/notify/allNotify`
export const monthlyData = `${host}/api/monthly/monthlyData`